CREATE TABLE CoreAccessLog(
 Cid int primary key identity NOT NULL,
 UserName nvarchar(300) NOT NULL,
 LogTimeStamp datetime2(7) NOT NULL,
 LogType nvarchar(100) NOT NULL,
 Result nvarchar(100) NULL,
 LogMessage nvarchar(3000) NULL,
)

CREATE TABLE CoreActionLog(
 Cid int primary key identity NOT NULL,
 UserName nvarchar(300) NULL,
 LogTimeStamp datetime2(7) NOT NULL,
 ControllerType nvarchar(100) NOT NULL,
 ControllerName nvarchar(100) NOT NULL,
 TableSource nvarchar(100) NULL,
 UserAction nvarchar(100) NOT NULL,
 LogMessage nvarchar(3000) NULL,
)

CREATE TABLE CoreErrorLog(
 Cid int primary key identity NOT NULL,
 UserName nvarchar(300) NULL,
 LogTimeStamp datetime2(7) NOT NULL,
 ErrorCode nvarchar(100) NULL,
 ControllerType nvarchar(100) NULL,
 ControllerName nvarchar(100) NULL,
 TableSource nvarchar(100) NULL,
 UserAction nvarchar(100) NULL,
 LogMessage nvarchar(3000) NULL,
 ErrorMessage nvarchar(max) NULL,
)

CREATE TABLE CoreUserMap(
 Cid int primary key identity NOT NULL,
 UserName nvarchar(500) NULL,
 EncryptedPassword nvarchar(2000) NULL,
)

CREATE TABLE CoreEmailInfo (
 Cid int primary key identity,
 TemplateName nvarchar(200) unique,
 EmailFrom nvarchar(2000),
 EmailTo nvarchar(2000),
 EmailCc nvarchar(2000),
 EmailBcc nvarchar(2000),
 EmailSubject nvarchar(500),
 EmailBody nvarchar(4000),
 EmailParameters nvarchar(4000),
 IsSent bit,
 AttachmentFilePaths nvarchar(4000),
)

CREATE TABLE CoreEmailTemplate (
 Cid int primary key identity,
 TemplateName nvarchar(200) unique,
 EmailFrom nvarchar(2000),
 EmailTo nvarchar(2000),
 EmailCc nvarchar(2000),
 EmailBcc nvarchar(2000),
 EmailSubject nvarchar(500),
 EmailBody nvarchar(4000),
 IsSent bit,
 AttachmentFilePaths nvarchar(4000),
)

INSERT INTO MetaItem (
TableName, DisplayName, TableSource, PrefilledColumns, ItemsPerPage, OrderBy, 
ActionList, DefaultActionList, TableActionList, DefaultTableActionList, 
TextFieldColumns, PictureColumns, IndexShownPictureColumns, RequiredColumns, NumberLimitColumns, 
RegexCheckedColumns, RegexCheckedColumnExamples, 
UserRelatedFilters, DisableFilter, ForcedFilterColumns, 
ColumnExclusionList, FilterExclusionList, DetailsExclusionList, CreateEditExclusionList, CsvExclusionList, AccessExclusionList, 
ColoringList, FilterDropDownLists, CreateEditDropDownLists, PrefixesOfColumns, PostfixesOfColumns, 
ListColumns, TimeStampColumns, HistoryTable, HistoryTrigger, AutoGeneratedColumns, 
ColumnSequence, ColumnAliases, EditShowOnlyColumns, ScriptConstructorColumns, ScriptColumns, 
CustomDateTimeFormatColumns, EmailMakerTriggers, EmailMakers, NonPictureAttachmentColumns, DownloadColumns, 
PreActionTriggers, PreActionProcedures, PostActionTriggers, PostActionProcedures, TableType, AggregationStatement
) VALUES (
'CoreAccessLog', --TableName
'Access Log',  --DisplayName
NULL, --TableSource
NULL,  --PrefilledColumns
15, --ItemsPerPage
'Cid', --OrderBy
'Create;Edit;Delete;Details', --ActionList
'Create;Edit;Delete;Details', --DefaultActionList
'ExportToCSV;ExportAllToCSV', --TableActionList
'ExportToCSV;ExportAllToCSV', --DefaultTableActionLinkList  
NULL, --TextFieldColumns
NULL, --PictureColumns
NULL, --IndexShownPictureColumns
NULL, --RequiredColumns
NULL, --NumberLimitColumns
NULL, --RegexCheckedColumns
NULL, --RegexCheckedColumnExamples
NULL, --UserRelatedFilters
NULL, --DisableFilter (bit)
NULL, --ForcedFilterColumns
'Cid', --ColumnExclusionList
NULL, --FilterExclusionList
'Cid', --DetailsExclusionList
NULL, --CreateEditExclusionList
NULL, --CsvExclusionList
'Anonymous;Administrator', --AccessExclusionList 
NULL, --ColoringList
NULL, --FilterDropDownLists 
NULL, --CreateEditDropDownLists
NULL, --PrefixesOfColumns 
NULL, --PostfixesOfColumns
NULL, --ListColumns
NULL, --TimeStampColumns
NULL, --HistoryTable
NULL, --HistoryTrigger
NULL, --AutoGeneratedColumns
NULL, --ColumnSequence
NULL, --ColumnAliases
NULL, --EditShowOnlyColumns
NULL, --ScriptConstructorColumns
NULL, --ScriptColumns
NULL, --CustomDateTimeFormatColumns
NULL, --EmailMakerTriggers
NULL, --EmailMakers
NULL, --NonPictureAttachmentColumns
NULL, --DownloadColumns
NULL, --PreActionTriggers
NULL, --PreActionProcedures
NULL, --PostActionTriggers
NULL, --PostActionProcedures
NULL, --TableType
NULL --AggregationStatement
)

INSERT INTO MetaItem (
TableName, DisplayName, TableSource, PrefilledColumns, ItemsPerPage, OrderBy, 
ActionList, DefaultActionList, TableActionList, DefaultTableActionList, 
TextFieldColumns, PictureColumns, IndexShownPictureColumns, RequiredColumns, NumberLimitColumns, 
RegexCheckedColumns, RegexCheckedColumnExamples, 
UserRelatedFilters, DisableFilter, ForcedFilterColumns, 
ColumnExclusionList, FilterExclusionList, DetailsExclusionList, CreateEditExclusionList, CsvExclusionList, AccessExclusionList, 
ColoringList, FilterDropDownLists, CreateEditDropDownLists, PrefixesOfColumns, PostfixesOfColumns, 
ListColumns, TimeStampColumns, HistoryTable, HistoryTrigger, AutoGeneratedColumns, 
ColumnSequence, ColumnAliases, EditShowOnlyColumns, ScriptConstructorColumns, ScriptColumns, 
CustomDateTimeFormatColumns, EmailMakerTriggers, EmailMakers, NonPictureAttachmentColumns, DownloadColumns, 
PreActionTriggers, PreActionProcedures, PostActionTriggers, PostActionProcedures, TableType, AggregationStatement
) VALUES (
'CoreActionLog', --TableName
'Action Log',  --DisplayName
NULL, --TableSource
NULL,  --PrefilledColumns
15, --ItemsPerPage
'Cid', --OrderBy
'Create;Edit;Delete;Details', --ActionList
'Create;Edit;Delete;Details', --DefaultActionList
'ExportToCSV;ExportAllToCSV', --TableActionList
'ExportToCSV;ExportAllToCSV', --DefaultTableActionLinkList  
NULL, --TextFieldColumns
NULL, --PictureColumns
NULL, --IndexShownPictureColumns
NULL, --RequiredColumns
NULL, --NumberLimitColumns
NULL, --RegexCheckedColumns
NULL, --RegexCheckedColumnExamples
NULL, --UserRelatedFilters
NULL, --DisableFilter (bit)
NULL, --ForcedFilterColumns
'Cid', --ColumnExclusionList
NULL, --FilterExclusionList
'Cid', --DetailsExclusionList
NULL, --CreateEditExclusionList
NULL, --CsvExclusionList
'Anonymous;Administrator', --AccessExclusionList 
NULL, --ColoringList
NULL, --FilterDropDownLists 
NULL, --CreateEditDropDownLists
NULL, --PrefixesOfColumns 
NULL, --PostfixesOfColumns
NULL, --ListColumns
NULL, --TimeStampColumns
NULL, --HistoryTable
NULL, --HistoryTrigger
NULL, --AutoGeneratedColumns
NULL, --ColumnSequence
NULL, --ColumnAliases
NULL, --EditShowOnlyColumns
NULL, --ScriptConstructorColumns
NULL, --ScriptColumns
NULL, --CustomDateTimeFormatColumns
NULL, --EmailMakerTriggers
NULL, --EmailMakers
NULL, --NonPictureAttachmentColumns
NULL, --DownloadColumns
NULL, --PreActionTriggers
NULL, --PreActionProcedures
NULL, --PostActionTriggers
NULL, --PostActionProcedures
NULL, --TableType
NULL --AggregationStatement
)

INSERT INTO MetaItem (
TableName, DisplayName, TableSource, PrefilledColumns, ItemsPerPage, OrderBy, 
ActionList, DefaultActionList, TableActionList, DefaultTableActionList, 
TextFieldColumns, PictureColumns, IndexShownPictureColumns, RequiredColumns, NumberLimitColumns, 
RegexCheckedColumns, RegexCheckedColumnExamples, 
UserRelatedFilters, DisableFilter, ForcedFilterColumns, 
ColumnExclusionList, FilterExclusionList, DetailsExclusionList, CreateEditExclusionList, CsvExclusionList, AccessExclusionList, 
ColoringList, FilterDropDownLists, CreateEditDropDownLists, PrefixesOfColumns, PostfixesOfColumns, 
ListColumns, TimeStampColumns, HistoryTable, HistoryTrigger, AutoGeneratedColumns, 
ColumnSequence, ColumnAliases, EditShowOnlyColumns, ScriptConstructorColumns, ScriptColumns, 
CustomDateTimeFormatColumns, EmailMakerTriggers, EmailMakers, NonPictureAttachmentColumns, DownloadColumns, 
PreActionTriggers, PreActionProcedures, PostActionTriggers, PostActionProcedures, TableType, AggregationStatement
) VALUES (
'CoreErrorLog', --TableName
'Error Log',  --DisplayName
NULL, --TableSource
NULL,  --PrefilledColumns
15, --ItemsPerPage
'Cid', --OrderBy
'Create;Edit;Delete;Details', --ActionList
'Create;Edit;Delete;Details', --DefaultActionList
'ExportToCSV;ExportAllToCSV', --TableActionList
'ExportToCSV;ExportAllToCSV', --DefaultTableActionLinkList  
NULL, --TextFieldColumns
NULL, --PictureColumns
NULL, --IndexShownPictureColumns
NULL, --RequiredColumns
NULL, --NumberLimitColumns
NULL, --RegexCheckedColumns
NULL, --RegexCheckedColumnExamples
NULL, --UserRelatedFilters
NULL, --DisableFilter (bit)
NULL, --ForcedFilterColumns
'Cid', --ColumnExclusionList
NULL, --FilterExclusionList
'Cid', --DetailsExclusionList
NULL, --CreateEditExclusionList
NULL, --CsvExclusionList
'Anonymous;Administrator', --AccessExclusionList 
NULL, --ColoringList
NULL, --FilterDropDownLists 
NULL, --CreateEditDropDownLists
NULL, --PrefixesOfColumns 
NULL, --PostfixesOfColumns
NULL, --ListColumns
NULL, --TimeStampColumns
NULL, --HistoryTable
NULL, --HistoryTrigger
NULL, --AutoGeneratedColumns
NULL, --ColumnSequence
NULL, --ColumnAliases
NULL, --EditShowOnlyColumns
NULL, --ScriptConstructorColumns
NULL, --ScriptColumns
NULL, --CustomDateTimeFormatColumns
NULL, --EmailMakerTriggers
NULL, --EmailMakers
NULL, --NonPictureAttachmentColumns
NULL, --DownloadColumns
NULL, --PreActionTriggers
NULL, --PreActionProcedures
NULL, --PostActionTriggers
NULL, --PostActionProcedures
NULL, --TableType
NULL --AggregationStatement
)

INSERT INTO MetaItem (
TableName, DisplayName, TableSource, PrefilledColumns, ItemsPerPage, OrderBy, 
ActionList, DefaultActionList, TableActionList, DefaultTableActionList, 
TextFieldColumns, PictureColumns, IndexShownPictureColumns, RequiredColumns, NumberLimitColumns, 
RegexCheckedColumns, RegexCheckedColumnExamples, 
UserRelatedFilters, DisableFilter, ForcedFilterColumns, 
ColumnExclusionList, FilterExclusionList, DetailsExclusionList, CreateEditExclusionList, CsvExclusionList, AccessExclusionList, 
ColoringList, FilterDropDownLists, CreateEditDropDownLists, PrefixesOfColumns, PostfixesOfColumns, 
ListColumns, TimeStampColumns, HistoryTable, HistoryTrigger, AutoGeneratedColumns, 
ColumnSequence, ColumnAliases, EditShowOnlyColumns, ScriptConstructorColumns, ScriptColumns, 
CustomDateTimeFormatColumns, EmailMakerTriggers, EmailMakers, NonPictureAttachmentColumns, DownloadColumns, 
PreActionTriggers, PreActionProcedures, PostActionTriggers, PostActionProcedures, TableType, AggregationStatement
) VALUES (
'CoreUserMap', --TableName
'User Map',  --DisplayName
NULL, --TableSource
NULL,  --PrefilledColumns
15, --ItemsPerPage
'Cid', --OrderBy
'Create;Edit;Delete;Details', --ActionList
'Create;Edit;Delete;Details', --DefaultActionList
'ExportToCSV;ExportAllToCSV', --TableActionList
'ExportToCSV;ExportAllToCSV', --DefaultTableActionLinkList  
NULL, --TextFieldColumns
NULL, --PictureColumns
NULL, --IndexShownPictureColumns
NULL, --RequiredColumns
NULL, --NumberLimitColumns
NULL, --RegexCheckedColumns
NULL, --RegexCheckedColumnExamples
NULL, --UserRelatedFilters
NULL, --DisableFilter (bit)
NULL, --ForcedFilterColumns
'Cid', --ColumnExclusionList
NULL, --FilterExclusionList
'Cid', --DetailsExclusionList
NULL, --CreateEditExclusionList
NULL, --CsvExclusionList
'Anonymous;Administrator', --AccessExclusionList 
NULL, --ColoringList
NULL, --FilterDropDownLists 
NULL, --CreateEditDropDownLists
NULL, --PrefixesOfColumns 
NULL, --PostfixesOfColumns
NULL, --ListColumns
NULL, --TimeStampColumns
NULL, --HistoryTable
NULL, --HistoryTrigger
NULL, --AutoGeneratedColumns
NULL, --ColumnSequence
NULL, --ColumnAliases
NULL, --EditShowOnlyColumns
NULL, --ScriptConstructorColumns
NULL, --ScriptColumns
NULL, --CustomDateTimeFormatColumns
NULL, --EmailMakerTriggers
NULL, --EmailMakers
NULL, --NonPictureAttachmentColumns
NULL, --DownloadColumns
NULL, --PreActionTriggers
NULL, --PreActionProcedures
NULL, --PostActionTriggers
NULL, --PostActionProcedures
NULL, --TableType
NULL --AggregationStatement
)

INSERT INTO MetaItem (
TableName, DisplayName, TableSource, PrefilledColumns, ItemsPerPage, OrderBy, 
ActionList, DefaultActionList, TableActionList, DefaultTableActionList, 
TextFieldColumns, PictureColumns, IndexShownPictureColumns, RequiredColumns, NumberLimitColumns, 
RegexCheckedColumns, RegexCheckedColumnExamples, 
UserRelatedFilters, DisableFilter, ForcedFilterColumns, 
ColumnExclusionList, FilterExclusionList, DetailsExclusionList, CreateEditExclusionList, CsvExclusionList, AccessExclusionList, 
ColoringList, FilterDropDownLists, CreateEditDropDownLists, PrefixesOfColumns, PostfixesOfColumns, 
ListColumns, TimeStampColumns, HistoryTable, HistoryTrigger, AutoGeneratedColumns, 
ColumnSequence, ColumnAliases, EditShowOnlyColumns, ScriptConstructorColumns, ScriptColumns, 
CustomDateTimeFormatColumns, EmailMakerTriggers, EmailMakers, NonPictureAttachmentColumns, DownloadColumns, PreActionTriggers, 
PreActionProcedures, PostActionTriggers, PostActionProcedures, TableType, AggregationStatement
) VALUES (
'CoreEmailInfo', --TableName
'Email Info',  --DisplayName
NULL, --TableSource
NULL,  --PrefilledColumns
15, --ItemsPerPage
'Cid', --OrderBy
'Create;Edit;Delete;Details', --ActionList
'Create;Edit;Delete;Details', --DefaultActionList
'ExportToCSV;ExportAllToCSV', --TableActionList
'ExportToCSV;ExportAllToCSV', --DefaultTableActionLinkList  
'EmailFrom;EmailTo;EmailSubject;EmailCc;EmailBcc;EmailBody=20;EmailParameters=20;AttachmentFilePaths', --TextFieldColumns
NULL, --PictureColumns
NULL, --IndexShownPictureColumns
NULL, --RequiredColumns
NULL, --NumberLimitColumns
NULL, --RegexCheckedColumns
NULL, --RegexCheckedColumnExamples
NULL, --UserRelatedFilters
NULL, --DisableFilter (bit)
NULL, --ForcedFilterColumns
'Cid;EmailCc;EmailBcc;EmailBody;EmailParameters;AttachmentFilePaths', --ColumnExclusionList
NULL, --FilterExclusionList
'Cid', --DetailsExclusionList
NULL, --CreateEditExclusionList
NULL, --CsvExclusionList
'Anonymous', --AccessExclusionList 
NULL, --ColoringList
NULL, --FilterDropDownLists 
NULL, --CreateEditDropDownLists
NULL, --PrefixesOfColumns 
NULL, --PostfixesOfColumns
NULL, --ListColumns
NULL, --TimeStampColumns
NULL, --HistoryTable
NULL, --HistoryTrigger
NULL, --AutoGeneratedColumns
NULL, --ColumnSequence
NULL, --ColumnAliases
NULL, --EditShowOnlyColumns
NULL, --ScriptConstructorColumns
NULL, --ScriptColumns
NULL, --CustomDateTimeFormatColumns
NULL, --EmailMakerTriggers
NULL, --EmailMakers
NULL, --NonPictureAttachmentColumns
NULL, --DownloadColumns
NULL, --PreActionTriggers
NULL, --PreActionProcedures
NULL, --PostActionTriggers
NULL, --PostActionProcedures
NULL, --TableType
NULL --AggregationStatement
)

INSERT INTO MetaItem (
TableName, DisplayName, TableSource, PrefilledColumns, ItemsPerPage, OrderBy, 
ActionList, DefaultActionList, TableActionList, DefaultTableActionList, 
TextFieldColumns, PictureColumns, IndexShownPictureColumns, RequiredColumns, NumberLimitColumns, 
RegexCheckedColumns, RegexCheckedColumnExamples, 
UserRelatedFilters, DisableFilter, ForcedFilterColumns, 
ColumnExclusionList, FilterExclusionList, DetailsExclusionList, CreateEditExclusionList, CsvExclusionList, AccessExclusionList, 
ColoringList, FilterDropDownLists, CreateEditDropDownLists, PrefixesOfColumns, PostfixesOfColumns, 
ListColumns, TimeStampColumns, HistoryTable, HistoryTrigger, AutoGeneratedColumns, 
ColumnSequence, ColumnAliases, EditShowOnlyColumns, ScriptConstructorColumns, ScriptColumns, 
CustomDateTimeFormatColumns, EmailMakerTriggers, EmailMakers, NonPictureAttachmentColumns, DownloadColumns, 
PreActionTriggers, PreActionProcedures, PostActionTriggers, PostActionProcedures, TableType, AggregationStatement
) VALUES (
'CoreEmailTemplate', --TableName
'Email Template',  --DisplayName
NULL, --TableSource
NULL,  --PrefilledColumns
15, --ItemsPerPage
'Cid', --OrderBy
'Create;Edit;Delete;Details', --ActionList
'Create;Edit;Delete;Details', --DefaultActionList
'ExportToCSV;ExportAllToCSV', --TableActionList
'ExportToCSV;ExportAllToCSV', --DefaultTableActionLinkList  
'EmailFrom;EmailTo;EmailSubject;EmailCc;EmailBcc;EmailBody=20;AttachmentFilePaths', --TextFieldColumns
NULL, --PictureColumns
NULL, --IndexShownPictureColumns
NULL, --RequiredColumns
NULL, --NumberLimitColumns
NULL, --RegexCheckedColumns
NULL, --RegexCheckedColumnExamples
NULL, --UserRelatedFilters
NULL, --DisableFilter (bit)
NULL, --ForcedFilterColumns
'Cid;EmailCc;EmailBcc;EmailBody;AttachmentFilePaths', --ColumnExclusionList
NULL, --FilterExclusionList
'Cid', --DetailsExclusionList
NULL, --CreateEditExclusionList
NULL, --CsvExclusionList
'Anonymous', --AccessExclusionList 
NULL, --ColoringList
NULL, --FilterDropDownLists 
NULL, --CreateEditDropDownLists
NULL, --PrefixesOfColumns 
NULL, --PostfixesOfColumns
NULL, --ListColumns
NULL, --TimeStampColumns
NULL, --HistoryTable
NULL, --HistoryTrigger
NULL, --AutoGeneratedColumns
NULL, --ColumnSequence
NULL, --ColumnAliases
NULL, --EditShowOnlyColumns
NULL, --ScriptConstructorColumns
NULL, --ScriptColumns
NULL, --CustomDateTimeFormatColumns
NULL, --EmailMakerTriggers
NULL, --EmailMakers
NULL, --NonPictureAttachmentColumns
NULL, --DownloadColumns
NULL, --PreActionTriggers
NULL, --PreActionProcedures
NULL, --PostActionTriggers
NULL, --PostActionProcedures
NULL, --TableType
NULL --AggregationStatement
)
