drop table CoreEmailInfo
drop table CoreEmailTemplate

USE [aiwe]
GO

/****** Object:  Table [dbo].[CoreEmailInfo]    Script Date: 10/26/2017 1:31:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CoreEmailInfo](
	[Cid] [int] IDENTITY(1,1) NOT NULL,
	[TemplateName] [nvarchar](200) NULL,
	[EmailFrom] [nvarchar](2000) NULL,
	[EmailTo] [nvarchar](2000) NULL,
	[EmailSubject] [nvarchar](500) NULL,
	[EmailCc] [nvarchar](2000) NULL,
	[EmailBcc] [nvarchar](2000) NULL,
	[EmailBody] [nvarchar](4000) NULL,
	[EmailParameters] [nvarchar](4000) NULL,
	[CreatedOn] [datetime2](7) NULL,
	[IsSent] [bit] NULL,
	[SendDateTime] [datetime] NULL,
	[SendCount] [int] NULL,
	[AttachmentFilePaths] [nvarchar](4000) NULL,
	[JobNo] [int] NULL,
	[JobStatus] [nvarchar](10) NULL,
	[ScheduleDateTime] [datetime2](7) NULL,
	[Send1DaysBefore] [int] NULL,
	[Send3DaysBefore] [int] NULL,
	[Send7DaysBefore] [int] NULL,
 CONSTRAINT [PK_EML_EMAILINFO] PRIMARY KEY CLUSTERED 
(
	[Cid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [aiwe]
GO

/****** Object:  Table [dbo].[CoreEmailTemplate]    Script Date: 10/26/2017 1:31:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CoreEmailTemplate](
	[Cid] [int] IDENTITY(1,1) NOT NULL,
	[TemplateName] [nvarchar](200) NULL,
	[EmailFrom] [nvarchar](2000) NULL,
	[EmailTo] [nvarchar](2000) NULL,
	[EmailSubject] [nvarchar](500) NULL,
	[EmailCc] [nvarchar](2000) NULL,
	[EmailBcc] [nvarchar](2000) NULL,
	[EmailBody] [nvarchar](4000) NULL,
	[CreatedOn] [nvarchar](200) NULL,
	[IsSent] [bit] NULL,
	[AttachmentFilePaths] [nvarchar](4000) NULL,
	[UpdatedBy] [nvarchar](50) NULL,
	[UpdatedOn] [datetime] NULL,
 CONSTRAINT [PK_EML_TEMPLATE] PRIMARY KEY CLUSTERED 
(
	[Cid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


insert into CoreEmailTemplate (TemplateName, EmailFrom, EmailTo, EmailSubject, 
EmailCc, EmailBcc, EmailBody, CreatedOn, IsSent, AttachmentFilePaths, UpdatedBy) 
values ('TEAM_ASSIGNED', --TemplateName
'@@User.UserName', --EmailFrom
'SQL-SCRIPT: use aiwe select Email from TestTableCommonA where OfficerName=@@Data.PersonInCharge', --EmailTo
'Team has been assigned', --EmailSubject
'SQL-SCRIPT: use aiweUsers select Email from AspNetUsers where (Team=@@User.Team or Team=''Home'') AND Email like ''%test.com''', --EmailCc
NULL, --EmailBcc
'This email is created @@Today, to assign you @@Data.PersonInCharge to work for @@Data.WorkHours hour(s).'+ CHAR(13) + 'Sent by @@User.FullName', --Email Body
'SQL-SCRIPT: SELCT GETDATE()', --CreatedOn
0, --IsSent
NULL, --AttachmentFilePaths
'admin' --UpdatedBy
)

delete from MetaItem where TableName = 'CoreEmailInfo'
delete from MetaItem where TableName = 'CoreEmailTemplate'

INSERT INTO MetaItem (TableName, DisplayName, TableSource, PrefilledColumns, ItemsPerPage, OrderBy, ActionList, DefaultActionList, TableActionList, DefaultTableActionList, TextFieldColumns, PictureColumns, IndexShownPictureColumns, RequiredColumns, NumberLimitColumns, RegexCheckedColumns, RegexCheckedColumnExamples, UserRelatedFilters, DisableFilter, ForcedFilterColumns, ColumnExclusionList, FilterExclusionList, DetailsExclusionList, CreateEditExclusionList, CsvExclusionList, AccessExclusionList, ColoringList, FilterDropDownLists, CreateEditDropDownLists, PrefixesOfColumns, PostfixesOfColumns, ListColumns, TimeStampColumns, HistoryTable, HistoryTrigger, AutoGeneratedColumns, ColumnSequence, ColumnAliases, EditShowOnlyColumns, ScriptConstructorColumns, ScriptColumns, CustomDateTimeFormatColumns, EmailMakerTriggers, EmailMakers) VALUES (
'CoreEmailInfo', --TableName
'Email',  --DisplayName
NULL, --TableSource
NULL,  --PrefilledColumns
15, --ItemsPerPage
'Cid', --OrderBy
'Create;Edit;Delete;Details', --ActionList
'Create;Edit;Delete;Details', --DefaultActionList
NULL, --TableActionList
NULL, --DefaultTableActionLinkList  
'EmailFrom;EmailTo;EmailSubject;EmailCc;EmailBcc;EmailBody=20;EmailParameters=20;AttachmentFilePaths', --TextFieldColumns
NULL, --PictureColumns
NULL, --IndexShownPictureColumns
NULL, --RequiredColumns
NULL, --NumberLimitColumns
NULL, --RegexCheckedColumns
NULL, --RegexCheckedColumnExamples
NULL, --UserRelatedFilters
NULL, --DisableFilter (bit)
NULL, --ForcedFilterColumns
'Cid;EmailCc;EmailBcc;EmailBody;EmailParameters;AttachmentFilePaths', --ColumnExclusionList
NULL, --FilterExclusionList
'Cid', --DetailsExclusionList
NULL, --CreateEditExclusionList
NULL, --CsvExclusionList
'Anonymous', --AccessExclusionList 
NULL, --ColoringList
NULL, --FilterDropDownLists 
NULL, --CreateEditDropDownLists
NULL, --PrefixesOfColumns 
NULL, --PostfixesOfColumns
NULL, --ListColumns
NULL, --TimeStampColumns
NULL, --HistoryTable
NULL, --HistoryTrigger
NULL, --AutoGeneratedColumns
NULL, --ColumnSequence
NULL, --ColumnAliases
NULL, --EditShowOnlyColumns
NULL, --ScriptConstructorColumns
NULL, --ScriptColumns
NULL, --CustomDateTimeFormatColumns
NULL, --EmailMakerTriggers
NULL, --EmailMakers
NULL, --NonPictureAttachmentColumns
NULL, --DownloadColumns
NULL, --PreActionTriggers
NULL, --PreActionProcedures
NULL, --PostActionTriggers
NULL, --PostActionProcedures
NULL, --TableType
NULL --AggregationStatement
)

INSERT INTO MetaItem (TableName, DisplayName, TableSource, PrefilledColumns, ItemsPerPage, OrderBy, ActionList, DefaultActionList, TableActionList, DefaultTableActionList, TextFieldColumns, PictureColumns, IndexShownPictureColumns, RequiredColumns, NumberLimitColumns, RegexCheckedColumns, RegexCheckedColumnExamples, UserRelatedFilters, DisableFilter, ForcedFilterColumns, ColumnExclusionList, FilterExclusionList, DetailsExclusionList, CreateEditExclusionList, CsvExclusionList, AccessExclusionList, ColoringList, FilterDropDownLists, CreateEditDropDownLists, PrefixesOfColumns, PostfixesOfColumns, ListColumns, TimeStampColumns, HistoryTable, HistoryTrigger, AutoGeneratedColumns, ColumnSequence, ColumnAliases, EditShowOnlyColumns, ScriptConstructorColumns, ScriptColumns, CustomDateTimeFormatColumns, EmailMakerTriggers, EmailMakers) VALUES (
'CoreEmailTemplate', --TableName
'Email Template',  --DisplayName
NULL, --TableSource
NULL,  --PrefilledColumns
15, --ItemsPerPage
'Cid', --OrderBy
'Create;Edit;Delete;Details', --ActionList
'Create;Edit;Delete;Details', --DefaultActionList
NULL, --TableActionList
NULL, --DefaultTableActionLinkList  
'EmailFrom;EmailTo;EmailSubject;EmailCc;EmailBcc;EmailBody=20;AttachmentFilePaths', --TextFieldColumns
NULL, --PictureColumns
NULL, --IndexShownPictureColumns
NULL, --RequiredColumns
NULL, --NumberLimitColumns
NULL, --RegexCheckedColumns
NULL, --RegexCheckedColumnExamples
NULL, --UserRelatedFilters
NULL, --DisableFilter (bit)
NULL, --ForcedFilterColumns
'Cid;EmailCc;EmailBcc;EmailBody;AttachmentFilePaths', --ColumnExclusionList
NULL, --FilterExclusionList
'Cid', --DetailsExclusionList
NULL, --CreateEditExclusionList
NULL, --CsvExclusionList
'Anonymous', --AccessExclusionList 
NULL, --ColoringList
NULL, --FilterDropDownLists 
NULL, --CreateEditDropDownLists
NULL, --PrefixesOfColumns 
NULL, --PostfixesOfColumns
NULL, --ListColumns
NULL, --TimeStampColumns
NULL, --HistoryTable
NULL, --HistoryTrigger
NULL, --AutoGeneratedColumns
NULL, --ColumnSequence
NULL, --ColumnAliases
NULL, --EditShowOnlyColumns
NULL, --ScriptConstructorColumns
NULL, --ScriptColumns
NULL, --CustomDateTimeFormatColumns
NULL, --EmailMakerTriggers
NULL, --EmailMakers
NULL, --NonPictureAttachmentColumns
NULL, --DownloadColumns
NULL, --PreActionTriggers
NULL, --PreActionProcedures
NULL, --PostActionTriggers
NULL, --PostActionProcedures
NULL, --TableType
NULL --AggregationStatement
)

