Create table TestTableCommonJ(
 Cid int primary key identity,
 Element1 nvarchar(200),
 Element2 nvarchar(200),
 IntItem1 int,
 IntItem2 int,
 DateTimeItem1 datetime2,
)

Create table TestTableCommonJ_History (
 Cid int primary key identity,
 Element1 nvarchar(200),
 ChangedNameElement2 nvarchar(200),
 IntItem1 int,
 DateTimeItem1 datetime2,
 AddElement1 nvarchar(200),
 CustomHRTS datetime2,
)

INSERT INTO MetaItem (TableName, DisplayName, TableSource, PrefilledColumns, ItemsPerPage, OrderBy, ActionList, DefaultActionList, TableActionList, DefaultTableActionList, TextFieldColumns, PictureColumns, IndexShownPictureColumns, RequiredColumns, NumberLimitColumns, RegexCheckedColumns, RegexCheckedColumnExamples, UserRelatedFilters, DisableFilter, ForcedFilterColumns, ColumnExclusionList, FilterExclusionList, DetailsExclusionList, CreateEditExclusionList, AccessExclusionList, ColoringList, FilterDropDownLists, CreateEditDropDownLists, PrefixesOfColumns, PostfixesOfColumns, ListColumns, TimeStampColumns, HistoryTable, HistoryTrigger, AutoGeneratedColumns, ColumnSequence, ColumnAliases, EditShowOnlyColumns, ScriptConstructorColumns, ScriptColumns, CustomDateTimeFormatColumns) VALUES (
'TestTableCommonJ', --TableName
'Original Table',  --DisplayName
NULL, --TableSource
NULL,  --PrefilledColumns
15, --ItemsPerPage
'Cid', --OrderBy
'Create;Edit;Delete;Details', --ActionList
'Create;Edit;Delete;Details', --DefaultActionList
NULL, --TableActionList
NULL, --DefaultTableActionLinkList  
NULL, --TextFieldColumns
NULL, --PictureColumns
NULL, --IndexShownPictureColumns
NULL, --RequiredColumns
NULL, --NumberLimitColumns
NULL, --RegexCheckedColumns
NULL, --RegexCheckedColumnExamples
NULL, --UserRelatedFilters
NULL, --DisableFilter (bit)
NULL, --ForcedFilterColumns
'Cid', --ColumnExclusionList
NULL, --FilterExclusionList
'Cid', --DetailsExclusionList
NULL, --CreateEditExclusionList
'Anonymous', --AccessExclusionList 
NULL, --ColoringList
NULL, --FilterDropDownLists 
NULL, --CreateEditDropDownLists
NULL, --PrefixesOfColumns 
NULL, --PostfixesOfColumns
NULL, --ListColumns
NULL, --TimeStampColumns
'TestTableCommonJ_History=Element1,Element2:ChangedNameElement2,IntItem1,DateTimeItem1,CustomHRTS:AUTO-GENERATED', --HistoryTable
'Element1=Element2 AND IntItem1=7000', --HistoryTrigger
NULL, --AutoGeneratedColumns
NULL, --ColumnSequence
NULL, --ColumnAliases
NULL, --EditShowOnlyColumns
NULL, --ScriptConstructorColumns
NULL, --ScriptColumns
NULL --CustomDateTimeFormatColumns
)

INSERT INTO MetaItem (TableName, DisplayName, TableSource, PrefilledColumns, ItemsPerPage, OrderBy, ActionList, DefaultActionList, TableActionList, DefaultTableActionList, TextFieldColumns, PictureColumns, IndexShownPictureColumns, RequiredColumns, NumberLimitColumns, RegexCheckedColumns, RegexCheckedColumnExamples, UserRelatedFilters, DisableFilter, ForcedFilterColumns, ColumnExclusionList, FilterExclusionList, DetailsExclusionList, CreateEditExclusionList, AccessExclusionList, ColoringList, FilterDropDownLists, CreateEditDropDownLists, PrefixesOfColumns, PostfixesOfColumns, ListColumns, TimeStampColumns, HistoryTable, HistoryTrigger, AutoGeneratedColumns, ColumnSequence, ColumnAliases, EditShowOnlyColumns, ScriptConstructorColumns, ScriptColumns, CustomDateTimeFormatColumns) VALUES (
'TestTableCommonJ_History', --TableName
'History Table',  --DisplayName
NULL, --TableSource
NULL,  --PrefilledColumns
15, --ItemsPerPage
'Cid', --OrderBy
'Create;Edit;Delete;Details', --ActionList
'Create;Edit;Delete;Details', --DefaultActionList
NULL, --TableActionList
NULL, --DefaultTableActionLinkList  
NULL, --TextFieldColumns
NULL, --PictureColumns
NULL, --IndexShownPictureColumns
NULL, --RequiredColumns
NULL, --NumberLimitColumns
NULL, --RegexCheckedColumns
NULL, --RegexCheckedColumnExamples
NULL, --UserRelatedFilters
NULL, --DisableFilter (bit)
NULL, --ForcedFilterColumns
'Cid', --ColumnExclusionList
NULL, --FilterExclusionList
'Cid', --DetailsExclusionList
NULL, --CreateEditExclusionList
'Anonymous', --AccessExclusionList 
NULL, --ColoringList
NULL, --FilterDropDownLists 
NULL, --CreateEditDropDownLists
NULL, --PrefixesOfColumns 
NULL, --PostfixesOfColumns
NULL, --ListColumns
NULL, --TimeStampColumns
NULL, --HistoryTable
NULL, --HistoryTrigger
NULL, --AutoGeneratedColumns
NULL, --ColumnSequence
NULL, --ColumnAliases
NULL, --EditShowOnlyColumns
NULL, --ScriptConstructorColumns
NULL, --ScriptColumns
NULL --CustomDateTimeFormatColumns
)

