using System.Collections.Generic;
using System.Linq;
using Aibe.Models;
using Aibe.Helpers;
//using Aiwe.Helpers;
using Extension.String;
using System.Data;
using System.Security.Principal;

namespace Aiwe.Models {
  public class CreateEditInfo : BaseTableInfo {
    //public TestMetaCommonTable Meta {
    //  get { return _meta; }
    //  set {
    //    _meta = value;

    //    pictureLinkColumns = _meta != null && !string.IsNullOrWhiteSpace(_meta.PictureLinkColumns) ?
    //      _meta.PictureLinkColumns.Split(';')?.Select(x => x.Split('=')[0].ToLower().Trim()).ToList() : null;

    //    createEditExclusionDescription = _meta != null && !string.IsNullOrWhiteSpace(_meta.CreateEditExclusionList) ?
    //      _meta.CreateEditExclusionList.Split(';')?.Select(x => x.Trim()).ToList() : null;
    //    createEditExclusion = _meta != null && !string.IsNullOrWhiteSpace(_meta.CreateEditExclusionList) ?
    //      _meta.CreateEditExclusionList.Split(';')?.Select(x => x.Split('=')[0].ToLower().Trim()).ToList() : null;

    //    if (_meta != null)
    //      assignDropdownColumns(_meta.CreateEditDropDownLists);

    //    textfieldColumnsDescription = _meta != null && !string.IsNullOrWhiteSpace(_meta.TextfieldColumns) ?
    //      _meta.TextfieldColumns.Split(';')?.Select(x => x.Trim()).ToList() : null;
    //    textfieldColumns = _meta != null && !string.IsNullOrWhiteSpace(_meta.TextfieldColumns) ?
    //      _meta.TextfieldColumns.Split(';')?.Select(x => x.Split('=')[0].ToLower().Trim()).ToList() : null;

    //    timestampColumnsDescription = _meta != null && !string.IsNullOrWhiteSpace(_meta.TimestampColumns) ?
    //      _meta.TimestampColumns.Split(';')?.Select(x => x.Trim()).ToList() : null;
    //    timestampColumns = _meta != null && !string.IsNullOrWhiteSpace(_meta.TimestampColumns) ?
    //      _meta.TimestampColumns.Split(';')?.Select(x => x.Split('=')[0].ToLower().Trim()).ToList() : null;
    //    TimestampColumnInfos = timestampColumnsDescription == null ?
    //      new List<TimeStampColumnInfo>() :
    //      timestampColumnsDescription.Select(x => new TimeStampColumnInfo(x)).Where(x => x.IsSuccess).ToList();

    //    historyTable = _meta != null && !string.IsNullOrWhiteSpace(_meta.HistoryTable) ? _meta.HistoryTable : string.Empty;
    //    historyTrigger = _meta != null && !string.IsNullOrWhiteSpace(_meta.HistoryTrigger) ? _meta.HistoryTrigger : string.Empty;

    //    autoGeneratedColumnsDescription = _meta != null && !string.IsNullOrWhiteSpace(_meta.AutoGeneratedColumns) ?
    //      _meta.AutoGeneratedColumns.Split(';')?.Select(x => x.Trim()).ToList() : null;
    //    autoGeneratedColumns = _meta != null && !string.IsNullOrWhiteSpace(_meta.AutoGeneratedColumns) ?
    //      _meta.AutoGeneratedColumns.Split(';')?.Select(x => x.Split('=')[0].ToLower().Trim()).ToList() : null;
    //    AutoGeneratedColumnInfos = autoGeneratedColumnsDescription == null ?
    //      new List<AutoGeneratedColumnInfo>() :
    //      autoGeneratedColumnsDescription.Select(x => new AutoGeneratedColumnInfo(x)).Where(x => x.IsSuccess).ToList();

    //    prefixesOfColumns = _meta != null && !string.IsNullOrWhiteSpace(_meta.PrefixesOfColumns) ?
    //      _meta.PrefixesOfColumns.Split(';')?.Select(x => x.Trim()).ToList() : null;
    //    prefixesColumns = prefixesOfColumns != null && prefixesOfColumns.Count > 0 ?
    //      prefixesOfColumns.Select(x => x.Split('=')[0].Trim()).ToList() : null;

    //    postfixesOfColumns = _meta != null && !string.IsNullOrWhiteSpace(_meta.PostfixesOfColumns) ?
    //      _meta.PostfixesOfColumns.Split(';')?.Select(x => x.Trim()).ToList() : null;
    //    postfixesColumns = postfixesOfColumns != null && postfixesOfColumns.Count > 0 ?
    //      postfixesOfColumns.Select(x => x.Split('=')[0].Trim()).ToList() : null;

    //    assignListColumns();
    //  }
    //}

    //private List<string> createEditExclusionDescription;
    //private List<string> createEditExclusion;
    //private List<string> textfieldColumnsDescription;
    //private List<string> textfieldColumns;
    //private List<string> prefixesOfColumns;
    //private List<string> prefixesColumns;
    //private List<string> postfixesOfColumns;
    //private List<string> postfixesColumns;
    //private List<string> timestampColumnsDescription;
    //private List<string> timestampColumns;
    //private string historyTable;
    //private string historyTrigger;
    //private List<string> autoGeneratedColumnsDescription;
    //private List<string> autoGeneratedColumns;

    public string ActionType { get; set; } = "create"; //create OR edit, default is create

    //public List<TimeStampColumnInfo> TimestampColumnInfos { get; private set; } //not needed, provided by meta
    public int CreateEditLabelPortion { get; private set; }

    public CreateEditInfo(MetaInfo metaInput, string actionType) : base(metaInput) {
      ActionType = actionType;
      List<string> columnNames = Meta.DataColumns.Select(x => x.ColumnName.ToCamelBrokenString()).ToList();
      CreateEditLabelPortion = columnNames.Any(x => x.Length >= 30) ? 3 : 2;
    }

    //Taken directly from Meta
    public string HistoryTable { get { return Meta.HistoryTable; } }
    public HistoryTriggerInfo HistorTrigger { get { return Meta.HistoryTrigger; } }
    public List<DropDownInfo> DropDowns { get { return Meta.CreateEditDropDowns; } }
    public List<AutoGeneratedColumnInfo> AutoGeneratedColumns { get { return Meta.AutoGeneratedColumns; } } //not needed, provided by meta
    public List<DataColumn> DataColumns { get { return Meta.DataColumns; } }

    //public CreateEditInfo(TestMetaCommonTable metaInput, List<DataColumn> columns, string actionType) {
    //  Meta = metaInput;
    //  Columns = columns;
    //  ActionType = actionType;
    //  List<string> columnNames = Columns.Select(x => x.ColumnName.ToCamelBrokenString()).ToList();
    //  CreateEditLabelPortion = columnNames.Any(x => x.Length >= 30) ? 3 : 2;
    //}

    public virtual bool IsColumnIncludedInCreateEdit(DataColumn column, IPrincipal user) {
      if (column.Unique || column.ColumnName.EqualsIgnoreCase("Cid")) //Cid and unique column always not included in the create and edit
        return false;
      if (Meta.CreateEditExclusions == null || Meta.CreateEditExclusions.Count <= 0) //if there is no column exclusion, then the column is definitely included
        return true;
      ExclusionInfo exInfo = Meta.CreateEditExclusions.FirstOrDefault(x => x.Name.EqualsIgnoreCaseTrim(column.ColumnName));
      if (exInfo == null) //non specified column exclusion is allowed
        return true; //means the column is include
      //explicitly excluded if the column is specified, without any roles specified
      bool isExplicitlyExcluded = exInfo.Roles == null || !exInfo.Roles.Any() || exInfo.Roles.Any(x => user.IsInRole(x)); 
      return !isExplicitlyExcluded; //if user is not explicitly excluded, then he is definitely included.
    }

    //public bool IsColumnIncludedInCreateEdit(DataColumn column, IPrincipal user) {
    //  bool isColumnIncluded = ActionFilterHelper.IsColumnIncluded(createEditExclusionDescription, column.ColumnName, user);
    //  if (column.Unique || column.ColumnName == "Cid" || //The default ones not included are Cid and unique column...
    //    (!isColumnIncluded && createEditExclusion != null && createEditExclusion.Contains(column.ColumnName.ToLower()))) //the advance one is controlled in the CreateEditExclusion            
    //    return false;
    //  return true;
    //}

    //public int GetTextFieldRowSize(string columnName) {
    //  return ActionFilterHelper.GetTextAreaRowSize(textfieldColumnsDescription, columnName);
    //}


    //public bool IsPictureLink(string columnName) {
    //  return pictureLinkColumns != null && pictureLinkColumns.Contains(columnName.ToLower());
    //}

  }
}