using System.Collections.Generic;
using System.Linq;
using Aibe.Models;
using Aibe.Models.Core;
using Extension.String;
using System.Data;
using System.Security.Principal;

namespace Aiwe.Models {
  public class CreateEditInfo : BaseTableInfo {
    public string ActionType { get; set; } = "create"; //create OR edit, default is create

    //public List<TimeStampColumnInfo> TimestampColumnInfos { get; private set; } //not needed, provided by meta
    public int CreateEditLabelPortion { get; private set; }

    public CreateEditInfo(MetaInfo metaInput, string actionType) : base(metaInput) {
      ActionType = actionType;
      //TODO, currently all these are hardcoded, not put in DH
      List<string> columnNames = Meta.ArrangedDataColumns.Select(x => Meta.GetColumnDisplayName(x.ColumnName)).ToList();
      CreateEditLabelPortion = columnNames.Any(x => x.Length >= 30) ? 3 : 2;
    }

    //Taken directly from Meta
    public string HistoryTable { get { return Meta.HistoryTable; } }
    public HistoryTriggerInfo HistorTrigger { get { return Meta.HistoryTrigger; } }
    public List<DropDownInfo> DropDowns { get { return Meta.CreateEditDropDowns; } }
    public List<AutoGeneratedColumnInfo> AutoGeneratedColumns { get { return Meta.AutoGeneratedColumns; } } //not needed, provided by meta

    public virtual bool IsColumnIncludedInCreateEdit(DataColumn column, IPrincipal user) {
      if (column.Unique || column.ColumnName.EqualsIgnoreCase("Cid")) //Cid and unique column always not included in the create and edit
        return false;
      return IsColumnIncluded(Meta.CreateEditExclusions, column.ColumnName, user);
    }
  }
}