using System.Collections.Generic;
using System.Linq;
using Extension.String;
using System.Data;
using Aibe.Models.DB;
using Aibe.Helpers;
using Extension.Database;
using System;

namespace Aibe.Models {
  public partial class MetaInfo {
    public string TableName { get; private set; }  
    public string TableDisplayName { get; private set; }
    public short ItemsPerPage { get; private set; } = 20; //give default value 20
    public List<OrderByInfo> OrderBys { get; private set; } = new List<OrderByInfo>();
    public List<ActionInfo> Actions { get; private set; } = new List<ActionInfo>();
    public List<string> DefaultActions { get; private set; } = new List<string>();
    public List<ActionInfo> TableActions { get; private set; } = new List<ActionInfo>();
    public List<string> DefaultTableActions { get; private set; } = new List<string>();
    public List<TextFieldColumnInfo> TextFieldColumns { get; private set; } = new List<TextFieldColumnInfo>();
    public List<PictureColumnInfo> PictureColumns { get; private set; } = new List<PictureColumnInfo>();
    public List<string> IndexShownPictureColumns { get; private set; } = new List<string>();
    public List<string> RequiredColumns { get; private set; } = new List<string>();
    public List<NumberLimitColumnInfo> NumberLimitColumns { get; private set; } = new List<NumberLimitColumnInfo>();
    public List<RegexCheckedColumnInfo> RegexCheckedColumns { get; private set; } = new List<RegexCheckedColumnInfo>();
    public List<RegexCheckedColumnExampleInfo> RegexCheckedColumnExamples { get; private set; } = new List<RegexCheckedColumnExampleInfo>();
    public List<UserRelatedFilterInfo> UserRelatedFilters { get; private set; } = new List<UserRelatedFilterInfo>();
    public bool FilterIsDisabled { get; private set; }
    public List<ExclusionInfo> ColumnExclusions { get; private set; } = new List<ExclusionInfo>();
    public List<ExclusionInfo> FilterExclusions { get; private set; } = new List<ExclusionInfo>();
    public List<ExclusionInfo> DetailsExclusions { get; private set; } = new List<ExclusionInfo>();
    public List<ExclusionInfo> CreateEditExclusions { get; private set; } = new List<ExclusionInfo>();
    public List<string> AccessExclusions { get; private set; } = new List<string>();
    public List<ColoringInfo> Colorings { get; private set; } = new List<ColoringInfo>();
    public List<DropDownInfo> FilterDropDowns { get; private set; } = new List<DropDownInfo>();
    public List<DropDownInfo> CreateEditDropDowns { get; private set; } = new List<DropDownInfo>();
    public List<AffixColumnInfo> PrefixesOfColumns { get; private set; } = new List<AffixColumnInfo>();
    public List<AffixColumnInfo> PostfixesOfColumns { get; private set; } = new List<AffixColumnInfo>();
    public List<ListColumnInfo> ListColumns { get; private set; } = new List<ListColumnInfo>();
    public List<TimeStampColumnInfo> TimeStampColumns { get; private set; } = new List<TimeStampColumnInfo>();
    public string HistoryTable { get; private set; }
    public HistoryTriggerInfo HistoryTrigger { get; private set; }
    public List<AutoGeneratedColumnInfo> AutoGeneratedColumns { get; private set; }


    //Extra properties
    public bool IsValid { get; private set; }
    public List<DataColumn> DataColumns { get; private set; } //This is just to get DataColumn, not DataRow, so that the info about this column in the database is known

    //Extra get-only properties
    public bool HasAction { get { return Actions != null && Actions.Any(); } }
    public bool HasCreateAction { get { return Actions != null && Actions.Any(x => x.Name.EqualsIgnoreCaseTrim(DH.CreateActionName)); } }
    public bool HasTableAction { get { return TableActions != null && TableActions.Any(); } }
    public List<ActionInfo> NonCreateActions { get { return Actions == null ? null : Actions.Where(x => !x.Name.EqualsIgnoreCaseTrim(DH.CreateActionName)).ToList(); } }
    public bool HasNonCreateAction { get { return Actions != null && Actions.Any(x => !x.Name.EqualsIgnoreCaseTrim(DH.CreateActionName)); } }

    public MetaInfo (MetaItem meta) {
      if (meta == null || string.IsNullOrWhiteSpace(meta.TableName)) //null meta makes an invalid item
        return;

      TableName = meta.TableName; 

      try { //do this as early as not to waste time... if we cannot proceed further
        DataColumns = SQLServerHandler.GetColumns(DH.DataDBConnectionString, TableName);
      } catch {
        //Invalid, do not use!
        return;
      }

      TableDisplayName = string.IsNullOrWhiteSpace(meta.DisplayName) ? meta.TableName.ToCamelBrokenString() :
          meta.DisplayName;
      ItemsPerPage = meta.ItemsPerPage == null ? (short)15 : meta.ItemsPerPage.Value;
      if (!string.IsNullOrWhiteSpace(meta.OrderBy))
        OrderBys = meta.OrderBy.GetTrimmedNonEmptyParts(';')
          .Select(x => new OrderByInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.ActionList))
        Actions = meta.ActionList.GetTrimmedNonEmptyParts(';')
          .Select(x => new ActionInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.DefaultActionList))
        DefaultActions = meta.DefaultActionList.GetTrimmedNonEmptyParts(';');
      if (!string.IsNullOrWhiteSpace(meta.TableActionList))
        TableActions = meta.TableActionList.GetTrimmedNonEmptyParts(';')
          .Select(x => new ActionInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.DefaultTableActionList))
        DefaultTableActions = meta.DefaultTableActionList.GetTrimmedNonEmptyParts(';');
      if (!string.IsNullOrWhiteSpace(meta.TextFieldColumns))
        TextFieldColumns = meta.TextFieldColumns.GetTrimmedNonEmptyParts(';')
          .Select(x => new TextFieldColumnInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.PictureColumns))
        PictureColumns = meta.PictureColumns.GetTrimmedNonEmptyParts(';')
          .Select(x => new PictureColumnInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.IndexShownPictureColumns))
        IndexShownPictureColumns = meta.IndexShownPictureColumns.GetTrimmedNonEmptyParts(';');
      if (!string.IsNullOrWhiteSpace(meta.RequiredColumns))
        RequiredColumns = meta.RequiredColumns.GetTrimmedNonEmptyParts(';');
      if (!string.IsNullOrWhiteSpace(meta.NumberLimitColumns))
        NumberLimitColumns = meta.NumberLimitColumns.GetTrimmedNonEmptyParts(';')
          .Select(x => new NumberLimitColumnInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.RegexCheckedColumns))
        RegexCheckedColumns = meta.RegexCheckedColumns.GetXMLTaggedInnerStrings("reg")
          .Select(x => new RegexCheckedColumnInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.RegexCheckedColumnExamples))
        RegexCheckedColumnExamples = meta.RegexCheckedColumnExamples.GetXMLTaggedInnerStrings("ex")
          .Select(x => new RegexCheckedColumnExampleInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.UserRelatedFilters))
        UserRelatedFilters = meta.UserRelatedFilters.GetTrimmedNonEmptyParts(';')
          .Select(x => new UserRelatedFilterInfo(x)).Where(x => x.IsValid).ToList(); //exclude non successful parsing result
      FilterIsDisabled = meta.DisableFilter != null && meta.DisableFilter.Value;
      if (!string.IsNullOrWhiteSpace(meta.ColumnExclusionList))
        ColumnExclusions = meta.ColumnExclusionList.GetTrimmedNonEmptyParts(';')
          .Select(x => new ExclusionInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.FilterExclusionList))
        FilterExclusions = meta.FilterExclusionList.GetTrimmedNonEmptyParts(';')
          .Select(x => new ExclusionInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.DetailsExclusionList))
        DetailsExclusions = meta.DetailsExclusionList.GetTrimmedNonEmptyParts(';')
          .Select(x => new ExclusionInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.CreateEditExclusionList))
        CreateEditExclusions = meta.CreateEditExclusionList.GetTrimmedNonEmptyParts(';')
          .Select(x => new ExclusionInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.AccessExclusionList))
        AccessExclusions = meta.AccessExclusionList.GetTrimmedNonEmptyParts(';');
      if (!string.IsNullOrWhiteSpace(meta.ColoringList))
        Colorings = meta.ColoringList.GetTrimmedNonEmptyParts(';')
          .Select(x => new ColoringInfo(x)).Where(x => x.IsValid).ToList();

      //For different dropdown columns: Info1;Info2;...;InfoN
      //Thus, symbol ";" cannot be in the where clause
      if (!string.IsNullOrWhiteSpace(meta.CreateEditDropDownLists))
        CreateEditDropDowns = meta.CreateEditDropDownLists.GetTrimmedNonEmptyParts(';')
          .Select(x => new DropDownInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.FilterDropDownLists))
        FilterDropDowns = meta.FilterDropDownLists.GetTrimmedNonEmptyParts(';')
          .Select(x => new DropDownInfo(x)).Where(x => x.IsValid).ToList();

      if (!string.IsNullOrWhiteSpace(meta.PrefixesOfColumns))
        PrefixesOfColumns = meta.PrefixesOfColumns.GetTrimmedNonEmptyParts(';')
          .Select(x => new AffixColumnInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.PostfixesOfColumns))
        PostfixesOfColumns = meta.PostfixesOfColumns.GetTrimmedNonEmptyParts(';')
          .Select(x => new AffixColumnInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.ListColumns))
        ListColumns = meta.ListColumns.GetTrimmedNonEmptyParts(';')
          .Select(x => new ListColumnInfo(x)).Where(x => x.IsValid).ToList();
      if (!string.IsNullOrWhiteSpace(meta.TimeStampColumns))
        TimeStampColumns = meta.TimeStampColumns.GetTrimmedNonEmptyParts(';')
          .Select(x => new TimeStampColumnInfo(x)).Where(x => x.IsValid).ToList();
      HistoryTable = meta.HistoryTable;
      if (!string.IsNullOrWhiteSpace(meta.HistoryTrigger)) {
        HistoryTriggerInfo testHistoryTrigger = new HistoryTriggerInfo(meta.HistoryTrigger);
        if (testHistoryTrigger.IsValid)
          HistoryTrigger = testHistoryTrigger;
      }
      if (!string.IsNullOrWhiteSpace(meta.AutoGeneratedColumns))
        AutoGeneratedColumns = meta.AutoGeneratedColumns.GetTrimmedNonEmptyParts(';')
          .Select(x => new AutoGeneratedColumnInfo(x)).Where(x => x.IsValid).ToList();

      IsValid = true; //Somehow, if failed before everything is finished, we cannot consider it as valid
    }

    //Extra methods
    #region ListColumns
    public bool IsListColumn(string columnName) {
      return ListColumns != null && ListColumns.Count > 0 &&
        ListColumns.Any(x => x.Name.EqualsIgnoreCaseTrim(columnName));
    }

    //Format: ServiceType=default|RefTableName:RefColumnName:RefOtherColumnName:ServiceStatus
    //there are two columns on the same table:
    // -> this column
    // -> changed Column name
    //The goal is to know if the changedColumn affect the column
    //if it changes to column, then the changed column must be at the last of the column
    public bool IsListColumnAffectedBy(string columnName, string changedColumnName) {
      if (string.IsNullOrWhiteSpace(columnName) || string.IsNullOrWhiteSpace(changedColumnName))
        return false;
      return ListColumns != null && ListColumns
        .Where(x => x.IsValid && x.RefInfo != null && !string.IsNullOrWhiteSpace(x.RefInfo.CrossTableCondColumn))
        .Any(x => x.Name.EqualsIgnoreCaseTrim(columnName) &&
          x.RefInfo.CrossTableCondColumn.EqualsIgnoreCaseTrim(changedColumnName));
    }

    //Must contain keyword "check" in the column description
    public bool IsListColumnOfType(string columnName, string type) {
      return ListColumns != null && ListColumns.Count > 0 && ListColumns.Any(
        x => x.Name.EqualsIgnoreCaseTrim(columnName) && x.ListType.EqualsIgnoreCaseTrim(type));
    }

    public string GetListColumnType(string columnName) {
      return ListColumns != null && ListColumns.Count > 0 && ListColumns.Any(
          x => x.Name.EqualsIgnoreCase(columnName)) ?
        ListColumns.FirstOrDefault(x => x.Name.EqualsIgnoreCaseTrim(columnName))?.ListType : null;
    }

    public bool ListColumnHasStaticTemplate(string columnName) {
      return ListColumns != null && ListColumns.Count > 0 && ListColumns.Any(
        x => x.RefInfo != null && //RInfo cannot be null
        !string.IsNullOrWhiteSpace(x.RefInfo.CondColumn) && //The condition column also cannot be null
        !string.IsNullOrWhiteSpace(x.RefInfo.StaticCrossTableCondColumn)); //lastly, there must be static value
    }

    public string GetColumnStaticTemplate(string columnName) {
      string dataValue = string.Empty;
      ListColumnInfo info = GetListColumnInfo(columnName);
      if (info == null)
        return null;
      bool result = info.GetRefDataValue(null, null, out dataValue);
      return result ? dataValue : null;
    }

    public ListColumnInfo GetListColumnInfo(string columnName) {
      return ListColumns == null ? null : ListColumns.FirstOrDefault(x => x.Name.EqualsIgnoreCaseTrim(columnName));
    }
    #endregion ListColumns

    #region PictureColumns
    public bool IsPictureColumn(string columnName) {
      return PictureColumns != null && PictureColumns.Count > 0 &&
        PictureColumns.Any(x => x.Name.EqualsIgnoreCaseTrim(columnName));
    }

    public bool IsIndexShownPictureColumn(string columnName) {
      return IndexShownPictureColumns != null && IndexShownPictureColumns.Count > 0 &&
        IndexShownPictureColumns.Any(x => x.EqualsIgnoreCaseTrim(columnName));
    }

    public int GetImageWidth(string columnName) {
      PictureColumnInfo info = PictureColumns.FirstOrDefault(x => x.Name.EqualsIgnoreCaseTrim(columnName));
      return info == null ? PictureColumnInfo.DefaultWidth : info.Width;
    }
    #endregion PictureColumns

    #region TextFieldColumns
    //If not specified, do not apply
    public bool IsTextField(string columnName) {
      return TextFieldColumns != null &&
        TextFieldColumns.Any(x => x.Name.EqualsIgnoreCase(columnName));
    }

    public int GetTextFieldRowSize(string columnName) {
      TextFieldColumnInfo info = TextFieldColumns.FirstOrDefault(x => x.Name.EqualsIgnoreCaseTrim(columnName));
      return info == null ? TextFieldColumnInfo.DefaultRowSize : info.RowSize;
    }
    #endregion TextFieldColumns

    #region TimeStampColumns
    //If not specified, do not apply
    public bool IsTimeStamp(string columnName) {
      return TimeStampColumns != null && !string.IsNullOrWhiteSpace(columnName) &&
        TimeStampColumns.Any(x => x.Name.EqualsIgnoreCase(columnName));
    }

    //If not specify, applied to all
    public bool IsTimeStampAppliedFor(string columnName, string actionName) {
      return IsTimeStamp(columnName) && !string.IsNullOrWhiteSpace(actionName) &&
        TimeStampColumns.Any(x => x.Name.EqualsIgnoreCase(columnName) &&
        (x.RowActionsApplied == null || x.RowActionsApplied.Count <= 0 ||
         x.RowActionsApplied.Any(y => y.Name.EqualsIgnoreCaseTrim(actionName))));
    }

    public bool IsTimeStampFixedFor(string columnName, string actionName) {
      return IsTimeStamp(columnName) && !string.IsNullOrWhiteSpace(actionName) &&
        TimeStampColumns.Any(x => x.Name.EqualsIgnoreCase(columnName) &&
        (x.RowActionsApplied == null || x.RowActionsApplied.Count <= 0 ||
         x.RowActionsApplied.Any(y => y.Name.EqualsIgnoreCaseTrim(actionName) && y.IsFixed)));
    }

    public int GetTimeStampShiftFor(string columnName, string actionName) {
      TimeStampColumnInfo info = IsTimeStamp(columnName) && !string.IsNullOrWhiteSpace(actionName) ?
        TimeStampColumns.FirstOrDefault(x => x.Name.EqualsIgnoreCase(columnName)) : null;
      if (info == null)
        return 0;
      TimeStampColumnRowActionInfo actInfo = info.RowActionsApplied.FirstOrDefault(x => x.Name.EqualsIgnoreCaseTrim(actionName));
      return actInfo == null ? 0 : (int)actInfo.ShiftValue;
    }
    #endregion TimeStampColumns

    #region AutoGeneratedColumns
    //If not specify, applied to all
    public bool IsAutoGenerated(string columnName) {
      return AutoGeneratedColumns != null && !string.IsNullOrWhiteSpace(columnName) &&
        AutoGeneratedColumns.Any(x => x.Name.EqualsIgnoreCase(columnName));
    }

    //If not specify, applied to all
    public bool IsAutoGeneratedAppliedFor(string columnName, string actionName) {
      return AutoGeneratedColumns != null && !string.IsNullOrWhiteSpace(columnName) &&
        !string.IsNullOrWhiteSpace(actionName) &&
        AutoGeneratedColumns.Any(x => x.Name.EqualsIgnoreCase(columnName) &&
        (x.TableColumnPairs == null || x.TableColumnPairs.Count <= 0 || //either table-column pair is not found
         x.TableColumnPairs.Any(y => y.Key.EqualsIgnoreCaseTrim(actionName)))); //or the action is found among the keys
    }
    #endregion AutoGeneratedColumns

    #region Affixes
    public string GetPrefix(string columnName) {
      AffixColumnInfo info = !string.IsNullOrWhiteSpace(columnName) ?
        PrefixesOfColumns.FirstOrDefault(x => x.Name.EqualsIgnoreCase(columnName)) : null;
      return info == null ? string.Empty : info.AffixValue;
    }

    public string GetPostfix(string columnName) {
      AffixColumnInfo info = !string.IsNullOrWhiteSpace(columnName) ?
        PostfixesOfColumns.FirstOrDefault(x => x.Name.EqualsIgnoreCase(columnName)) : null;
      return info == null ? string.Empty : info.AffixValue;
    }
    #endregion Affixes

    #region DropDownColumns
    public DropDownInfo GetCreateEditDropDownColumnInfo(string columnName) {
      return getDropDownColumnInfo(CreateEditDropDowns, columnName);
    }

    public DropDownInfo GetFilterDropDownColumnInfo(string columnName) {
      return getDropDownColumnInfo(FilterDropDowns, columnName);
    }

    private DropDownInfo getDropDownColumnInfo(List<DropDownInfo> dropdowns, string columnName) {
      return dropdowns == null ? null : dropdowns.FirstOrDefault(x => x.Name.EqualsIgnoreCase(columnName));
    }

    public bool IsCreateEditDropDownColumn(string columnName) {
      return isDropDownColumn(CreateEditDropDowns, columnName);
    }

    public bool IsFilterDropDownColumn(string columnName) {
      return isDropDownColumn(FilterDropDowns, columnName);
    }

    private bool isDropDownColumn(List<DropDownInfo> dropdowns, string columnName) {
      return dropdowns != null && dropdowns.Count > 0 && dropdowns.Any(x => x.Name.EqualsIgnoreCase(columnName));
    }

    public bool IsCreateEditDropDownColumnAffectedBy(string columnName, string changedColumnName) {
      return isDropdownColumnAffectedBy(CreateEditDropDowns, columnName, changedColumnName);
    }

    //TODO By right, this should not be called in filter, but prepare first just in case
    public bool IsFilterDropDownColumnAffectedBy(string columnName, string changedColumnName) {
      return isDropdownColumnAffectedBy(FilterDropDowns, columnName, changedColumnName);
    }

    private bool isDropdownColumnAffectedBy(List<DropDownInfo> dropdowns, string columnName, string changedColumnName) {
      if (string.IsNullOrWhiteSpace(columnName) || string.IsNullOrWhiteSpace(changedColumnName))
        return false;
      var possibleColumns = dropdowns //possible columns
        .Where(x => x.Name.EqualsIgnoreCase(columnName) &&
          x.Items != null && x.Items.Count > 0 &&
          x.Items.Any(y => y.RefInfo != null &&
            !string.IsNullOrWhiteSpace(y.RefInfo.CrossTableCondColumn)));
      if (!possibleColumns.Any()) //if there is nothing, returns false immediately
        return false;
      if (possibleColumns.Any(x => x.Items.Any(y => y.RefInfo != null &&
          y.RefInfo.CrossTableCondColumn.EqualsIgnoreCaseTrim(changedColumnName))))
        return true;

      foreach (var col in possibleColumns)
        foreach (var rInfo in col.Items.Where(x => x.RefInfo != null).Select(x => x.RefInfo)) { //containing addtional where clauses
          if (string.IsNullOrWhiteSpace(rInfo.AdditionalWhereClause))
            continue;
          var matches = DropDownHelper.VarToValRegex.Matches(rInfo.AdditionalWhereClause);
          if (matches.Count <= 0)
            continue;
          foreach (var match in matches) {
            string checkedMatch = DropDownHelper.GetCheckedMatch(match);
            if (checkedMatch.EqualsIgnoreCase(changedColumnName))
              return true; //only if there is match such as this the column is considered affected by the change
          }
        }
      return false;
    }
    #endregion DropDownColumns

    #region Actions and TableActions
    public bool IsDefaultAction(string actionName) {
      return DefaultActions != null && DefaultActions.Any(x => x.EqualsIgnoreCaseTrim(actionName));
    }

    public bool IsDefaultTableAction(string tableActionName) {
      return DefaultTableActions != null && DefaultTableActions.Any(x => x.EqualsIgnoreCaseTrim(tableActionName));
    }
    #endregion Actions and TableActions

    #region Regexes
    public RegexCheckedColumnInfo GetRegexCheckedColumn(string columnName) {
      return RegexCheckedColumns == null ? null : RegexCheckedColumns.FirstOrDefault(x => x.Name.EqualsIgnoreCase(columnName));
    }

    public RegexCheckedColumnExampleInfo GetRegexCheckedColumnExample(string columnName) {
      return RegexCheckedColumnExamples == null ? null : RegexCheckedColumnExamples.FirstOrDefault(x => x.Name.EqualsIgnoreCase(columnName));
    }

    public bool IsRegexCheckedColumn(string columnName) {
      return RegexCheckedColumns != null && RegexCheckedColumns.Any(x => x.Name.EqualsIgnoreCase(columnName));
    }

    public bool IsRegexCheckedColumnExample(string columnName) {
      return RegexCheckedColumnExamples != null && RegexCheckedColumnExamples.Any(x => x.Name.EqualsIgnoreCase(columnName));
    }
    #endregion Regexes

    #region NumberLimits
    public NumberLimitColumnInfo GetNumberLimitColumn(string columnName) {
      return NumberLimitColumns == null ? null : NumberLimitColumns.FirstOrDefault(x => x.Name.EqualsIgnoreCase(columnName));
    }

    public bool IsNumberLimitColumn(string columnName) {
      return NumberLimitColumns != null && NumberLimitColumns.Any(x => x.Name.EqualsIgnoreCase(columnName));
    }
    #endregion NumberLimits
  }
}