namespace Aibe.Models.Filters {
  // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
  public partial class MetaFilter : BaseFilter {
    public string TableName { get; set; }
    public string DisplayName { get; set; }
    public short? ItemsPerPageFrom { get; set; }
    public short? ItemsPerPageTo { get; set; }
    public string OrderBy { get; set; }
    public string ActionList { get; set; }
    public string DefaultActionList { get; set; }
    public string TableActionList { get; set; }
    public string DefaultTableActionList { get; set; }
    public string TextFieldColumns { get; set; }
    public string PictureColumns { get; set; }
    public string IndexShownPictureColumns { get; set; }
    public string RequiredColumns { get; set; }
    public string NumberLimitColumns { get; set; }
    public string RegexCheckedColumns { get; set; }
    public string RegexCheckedColumnExamples { get; set; }
    public string UserRelatedFilters { get; set; }
    public string DisableFilter { get; set; }
    public string ColumnExclusionList { get; set; }
    public string FilterExclusionList { get; set; }
    public string DetailsExclusionList { get; set; }
    public string CreateEditExclusionList { get; set; }
    public string AccessExclusionList { get; set; }
    public string ColoringList { get; set; }
    public string FilterDropDownLists { get; set; }
    public string CreateEditDropDownLists { get; set; }
    public string PrefixesOfColumns { get; set; }
    public string PostfixesOfColumns { get; set; }
    public string ListColumns { get; set; }
    public string TimeStampColumns { get; set; }
    public string HistoryTable { get; set; }
    public string HistoryTrigger { get; set; }
    public string AutoGeneratedColumns { get; set; }
  }
}