using System.Collections.Generic;
using System.Linq;
using Extension.String;

namespace Aibe.Models.Core {
  public partial class AutoGeneratedColumnInfo : CommonBaseInfo {
    private static List<string> allowedAutoGenerated = new List<string> { DH.CreateActionName, DH.EditActionName }; //only allows create and edit actions for now
    public Dictionary<string, string> TableColumnPairs { get; private set; } = new Dictionary<string, string>();
    public AutoGeneratedColumnInfo(string desc) : base(desc) {
      if (HasRightSide) {
        var rightParts = desc.GetTrimmedNonEmptyParts(',');
        foreach(var rightPart in rightParts) {
          var pairs = rightPart.GetTrimmedNonEmptyParts(':');
          if (pairs.Count < 2)
            continue;
          if (allowedAutoGenerated.Any(x => x.EqualsIgnoreCase(pairs[0]))) //can only add whatever is allowed in the autogeneration
            TableColumnPairs.Add(pairs[0], pairs[1]); //adds every valid pair
        }
      }
    }
  }
}